learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
from django.urls import path
from . import views


app_name = 'learning_logs'
urlpatterns = [
    # Homepage
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    # Detail for a single topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Add a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    #Page for adding a new entry
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),
    #Page for editing an entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    # Include the default auth urls
    path('', include('django.contrib.auth.urls')),
    
    #Registration page
    path('register/', views.register, name='register'),

    # path('logout/', views.logout, name='logout'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        """Return as tring representation of the model"""
        return self.text


"""Many entries is associated with one topic: many-to-one-relationship"""


class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        # if len(self.text.split()) >= 50:
        if len(self.text) >= 50:
            return f"{self.text[:50]}..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from . models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}
        
        
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404
from . models import Topic, Entry
from . forms import TopicForm, EntryForm


def check_topic_owner():
    pass 


def index(request):
    """The homepage for Learning Log"""
    return render(request, 'learning_logs/index.html')


@login_required(login_url='login')
def topics(request):
    """Show all topics"""
    topics = Topic.objects.filter(owner=request.user).order_by(
        'date_added')  # only show d user with d associated topic
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required(login_url='login')
def topic(request, topic_id):
    """Show a single topic and all its entries"""
    # topic = Topic.objects.get(id=topic_id)
    topic = get_object_or_404(Topic, id=topic_id)
    
    # Make sure the topic belongs to the current user
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required(login_url='login')
def new_topic(request):
    """Add a new topic"""
    if request.method != 'POST':
        # No data is submitted create a blank form
        form = TopicForm()
    else:
        # POST data submitted; process data
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')

    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required(login_url='login')
def new_entry(request, topic_id):
    """Add a new entry for a particular topic"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted, create a blank form
        form = EntryForm()
    else:
        # prepopulated with d post data from the request object
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    # Display a blank or invalid form
    context = {'form': form, 'topic': topic}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required(login_url='login')
def edit_entry(request, entry_id):
    """Edit an existing entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic  # get the topic associated with d entry
    
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request, pre-fill form with the current entry
        # create d form prefilled with information from the existing entry object
        form = EntryForm(instance=entry)
    else:
        # POST data submitted, process data
        # create an entry object updated with d relevant data
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            edit_entry = form.save(commit=False)
            edit_entry.owner = request.user
            edit_entry.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm


def logout(request):
    return render(request, 'registration/logged_out.html')

def register(request):
    """Register a new user"""
    if request.method != 'POST':
    #Display blank registration form
        form = UserCreationForm()
    else:
        #Process completed form
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            #Log the user in and then redirect to home page
            login(request, new_user)  #instead can show the user a login registration form
            return redirect('learning_logs:index')
        
    #Display a blank or invalid form
    context = {'form': form}
    return render(request, 'registration/register.html', context)
    
    

learning_logs/templates/learning_logs/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Learning Log</title>
    <link rel="stylesheet" href="{% static 'normalize.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <div class="nav">
        <div class="left-section">
            <li class="learning-log"><a href="{% url 'learning_logs:index' %}">Learning Log</a></li>
            <li class="topics"><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
        </div>

        <div class="right-section">
            {% if user.is_authenticated %}
            <li>Hello, {{ user.username }}</li>
            <li><a href="{% url 'logout' %}">Log out</a></li>
            {% else %}
            <li class="register"><a href="{% url 'register' %}">Register</a></li>
            <li class="login"><a href="{% url 'login' %}">Log in</a></li>
            {% endif %}
        </div>
    </div>
</body>
</html>

{% block content %} {% endblock %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p>
    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
</p>

<p>Edit entry:</p>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" name="'submit">Save changes</button>
</form>

{% endblock %}

learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Learning Log</title>
    </head>
    <body>
    {% extends 'learning_logs/base.html' %} 
    {% block content %}
    
    <div class="container">
        <h1 class="header">Track your learning.</h1>
        <p class="content">
            Make your own Learning Log, and keep a list of the topics you're learning about.
            Whenever you learn something new about a topic, make an entry summarizing what you've learned.
        </p>
        <button class="btn"><a href="{% url 'register' %}">Register &#62;&#62;</a></button>
    </div>
    
    {% endblock %}
    </body>
</html>

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Add a new entry:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" name="submit">Add entry</button>
</form>

{% endblock %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p>Add a new topic:</p>

<form action="{% url 'learning_logs:new_topic' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit" type="submit">Add topic</button>
</form>

{% endblock %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p>Topic: {{ topic }}</p>

<p>Entries:</p>
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
</p>

<ul>
    {% for entry in entries %}
    <li>
        <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ entry.text|linebreaks }}</p>
        <p>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>
        </p>
    </li>
    {% empty %}
    <li>There are no entries for this topic yet.</li>
    {% endfor %}
</ul>
{% endblock %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p>Topics</p>

<ul>
    {% for topic in topics %}
    <li>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </li>
    {% empty %}
    <li>No topics has been added yet.</li>
    {% endfor %}
</ul>

<a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>

{% endblock %}